apiVersion: v1
kind: Service
metadata:
  labels:
    app: supermario-argocd
  name: supermario-argocd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: supermario-argocd
  sessionAffinity: None
  type: ClusterIP
